### ISSUE TITLE
Unable to successfully transfer players to fall back server

### ISSUE THREAD

**Issue by rewsdjad1** [sasi2006166/Fallback-Server#2]
```

[15:21:14 ERROR]: [luxia_guer|/127.0.0.1:64882] <-> ServerConnector [Lobby1] - encountered exception
java.lang.ClassCastException: class se.llbit.nbt.NamedTag cannot be cast to class java.lang.Integer (se.llbit.nbt.NamedTag is in unnamed module of loader 'app'; java.lang.Integer is in module java.base of loader 'bootstrap')
        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:334) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:198) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[15:21:14 INFO]: [luxia_guer|/127.0.0.1:64882] <-> ServerConnector [Lobby1] has disconnected
[15:22:13 ERROR]: io.netty.handler.timeout.ReadTimeoutException
```

When I shut down a server, the title was successfully displayed. The player is still stuck in that server, and he can still place and destroy blocks. After a long time, the player will be kicked out due to the Read timed out.

(Sorry for my bad english)

**Comment by sasi2006166** [comment]
Hello, apparently there are some kind of bungeecord configuration issues and for now my plugin only supports ONE lobby. 

Can you please send me the config.yml of your bungeecord server and the config of my plugin? 

Thanks.

**Comment by rewsdjad1** [comment]
> Hello, apparently there are some kind of bungeecord configuration issues and for now my plugin only supports ONE lobby.
> 
> Can you please send me the config.yml of your bungeecord server and the config of my plugin?
> 
> Thanks.

[config bungee.txt](https://github.com/sasi2006166/Fallback-Server/files/6853324/config.bungee.txt)
[config fallbackserver.txt](https://github.com/sasi2006166/Fallback-Server/files/6853327/config.fallbackserver.txt)

I changed it to a txt file for upload.
I know there can only be one fallback server, but my subserver is just named "Lobby1".

**Comment by sasi2006166** [comment]
Hello, apparently I don't see any kind of error in code, I need a list of your plugins (bungeecord side). 

Thanks.

**Comment by rewsdjad1** [comment]
https://pastebin.com/kiTeQgXq
All my plugins including modules in bungeecord are here.
I used the dump function of other plugins to allow you to see more clearly.

**Comment by sasi2006166** [comment]
Error, this is a private paste or is pending moderation. If this paste belongs to you, please login to Pastebin to view it.

From pastebin.

**Comment by rewsdjad1** [comment]
Sorry, I set it wrong, try again now

**Comment by sasi2006166** [comment]
Okay maybe I see the issue. 

Remove protocolize plugin and try using fallback server (the issue is coming from that plugin most probably) . 

Also i don't recommend to use viarewind/version and other into bungeecord, transfer those spigot side to avoid performance issues. 


That plugin is causing so many problems with "pl-hide-pro", i don't think that the developer of those plugins knows that, anyway, for now remove those two plugins (or only protocolize) and see if works.

**Comment by rewsdjad1** [comment]
```
[11:26:03 INFO]: [.luxiaguer|/192.168.0.129:63440] <-> ServerConnector [Lobby1] has connected
[11:26:03 INFO]: [/192.168.0.129:63440|.luxiaguer] <-> DownstreamBridge <-> [Sur1] has disconnected
[11:26:03 ERROR]: [.luxiaguer|/192.168.0.129:63440] <-> ServerConnector [Lobby1] - encountered exception
java.lang.ClassCastException: class se.llbit.nbt.NamedTag cannot be cast to class java.lang.Integer (se.llbit.nbt.NamedTag is in unnamed module of loader 'app'; java.lang.Integer is in module java.base of loader 'bootstrap')
        at net.md_5.bungee.ServerConnector.handle(ServerConnector.java:334) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at net.md_5.bungee.protocol.packet.Login.handle(Login.java:198) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:111) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall-1.17-445.jar:git:Waterfall-Bootstrap:1.17-R0.1-SNAPSHOT:e6526b1:445]
        at java.lang.Thread.run(Thread.java:831) [?:?]
[11:26:03 INFO]: [.luxiaguer|/192.168.0.129:63440] <-> ServerConnector [Lobby1] has disconnected
[11:26:04 INFO] [LuckPerms]: [Messaging] Received user update ping for '.luxiaguer' with id: ac45fd84-ee0b-4996-b4a5-1beb5757b64c
[11:26:15 INFO] [Geyser-BungeeCord]: 基岩版IP为: /192.168.0.129 的玩家因 CLOSED_BY_REMOTE_PEER 断开连接
[11:26:15 INFO] [Geyser-BungeeCord]: luxiaguer 因 CLOSED_BY_REMOTE_PEER 从远程Java服务器 127.0.0.1 断开
[11:26:15 INFO]: [/192.168.0.129:63440|.luxiaguer] -> UpstreamBridge has disconnected
```

Nothing happened, still show this.

This is what the player sees, both java and geyser users are like this:
![image](https://user-images.githubusercontent.com/79432245/126541596-e7534e71-e08e-40cd-bcd0-c44ea77808bf.png)

**Comment by sasi2006166** [comment]
Do you have "chunky" plugin spigot side?

**Comment by rewsdjad1** [comment]
No, it doesn't even support my server [1.12.2].

**Comment by sasi2006166** [comment]
Apparently the problem is coming from both (i think) bungeecord side and spigot side, my plugin isn't giving any error.

Contact me on discord, CandiesJar#0347

**Comment by rewsdjad1** [comment]
The user cannot be found, it seems that you forgot to enter one of the numbers

**Comment by rewsdjad1** [comment]
The problem has been resolved. It seems that viaversion is in conflict with geyser, or it is completely the problem of viaversion being installed and bungeecord.

**Comment by sasi2006166** [comment]
Issue has been solved, thanks for collaboration.
