### ISSUE TITLE
ERROR 

### ISSUE THREAD

**Issue by trazodana** [sasi2006166/Fallback-Server#31]
20:15:47 ERROR]: [/94.63.67.128:51522|Frank] -> UpstreamBridge - encountered exception
java.lang.NullPointerException: Cannot invoke "net.md_5.bungee.protocol.MinecraftDecoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null
        at net.md_5.bungee.netty.ChannelWrapper.getDecodeProtocol(ChannelWrapper.java:41) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at net.md_5.bungee.connection.UpstreamBridge.configureServer(UpstreamBridge.java:382) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:376) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at net.md_5.bungee.protocol.packet.StartConfiguration.handle(StartConfiguration.java:35) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:124) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at com.nickuc.antibot.μΣξολψηΔξγυΦν.channelRead(:63) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at com.nickuc.antibot.ΠθκονθΛλαχςΔ.channelRead(:29) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:93) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at com.nickuc.antibot.ΛδνδπΛζψηξαρΨ.channelRead(:27) ~[?:?]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:509) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:407) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[server.jar:git:Waterfall-Bootstrap:1.20-R0.2-SNAPSHOT:92b5149:562]
        at java.lang.Thread.run(Thread.java:840) [?:?]
[20:15:47 INFO]: [Frank] disconnected with: NullPointerException : Cannot invoke "net.md_5.bungee.protocol.MinecraftDecoder.getProtocol()" because the return value of "io.netty.channel.ChannelPipeline.get(java.lang.Class)" is null @ net.md_5.bungee.netty.ChannelWrapper:41

**Comment by sasi2006166** [comment]
Hello, this error is caused by an outdated bungeecord version, just update it to latest and you're good to go.

**Comment by trazodana** [comment]
> Hello, this error is caused by an outdated bungeecord version, just update it to latest and you're good to go.

But waterfall is in its latest version!
