### ISSUE TITLE
Hub command error (velocity)

### ISSUE THREAD

**Issue by jonaas13** [sasi2006166/Fallback-Server#37]
I'm having an issue with the hub command on the latest velocity. I already updated limboapi.

`java.util.concurrent.CompletionException: java.lang.RuntimeException: Unable to invoke command hub for [connected player] jonaas13 (/80.57.157.147:52489)
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
Caused by: java.lang.RuntimeException: Unable to invoke command hub for [connected player] jonaas13 (/80.57.157.147:52489)
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:252) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:279) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more
Caused by: java.lang.NullPointerException: Cannot invoke "com.velocitypowered.api.proxy.server.RegisteredServer.getServerInfo()" because "server" is null
        at me.candiesjar.fallbackserver.commands.base.HubCommand.lambda$execute$0(HubCommand.java:63) ~[?:?]
        at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672) ~[?:?]
        at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?]
        at me.candiesjar.fallbackserver.commands.base.HubCommand.execute(HubCommand.java:63) ~[?:?]
        at me.candiesjar.fallbackserver.commands.base.HubCommand.execute(HubCommand.java:22) ~[?:?]
        at com.velocitypowered.proxy.command.registrar.InvocableCommandRegistrar.lambda$createLiteral$1(InvocableCommandRegistrar.java:81) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:262) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.executeImmediately0(VelocityCommandManager.java:230) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.command.VelocityCommandManager.lambda$executeImmediatelyAsync$1(VelocityCommandManager.java:279) ~[velocity.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        ... 3 more`

**Comment by BakiDance** [comment]
Also getting this on my network. /hub works only if you're already connected to the hub server (which is about as useful as it seems) then stops working the moment the player switches to another server.

**Comment by Ammutadori075** [comment]
Same problem here
