### ISSUE TITLE
velocity startup plugin error

### ISSUE THREAD

**Issue by HYDeath** [sasi2006166/Fallback-Server#38]
Core: velocity-3.3.0-SNAPSHOT-390
Version: FallBackServerVelocity-3.2.0-Beta2
Error Reporting Content:

[00:03:35 ERROR]: Couldn't pass ProxyInitializeEvent to fallbackservervelocity 3.2.0-Beta2
java.lang.RuntimeException: Failed to download library 'me.carleslc.Simple-YAML:Simple-Yaml:1.8.4'
        at me.candiesjar.fallbackserver.libs.net.byteflux.libby.LibraryManager.downloadLibrary(LibraryManager.java:525) ~[?:?]
        at me.candiesjar.fallbackserver.libs.net.byteflux.libby.LibraryManager.loadLibrary(LibraryManager.java:585) ~[?:?]
        at me.candiesjar.fallbackserver.FallbackServerVelocity.loadDependencies(FallbackServerVelocity.java:168) ~[?:?]
        at me.candiesjar.fallbackserver.FallbackServerVelocity.onProxyInitialization(FallbackServerVelocity.java:107) ~[?:?]
        at me.candiesjar.fallbackserver.Lmbda$1.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity-3.3.0-SNAPSHOT-390.jar:3.3.0-SNAPSHOT (git-afd8b55f-b390)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]

**Comment by Magicrafter13** [comment]
How was this fixed?
