### ISSUE TITLE
Fallback server doesn't send players to the fallback server

### ISSUE THREAD

**Issue by BakiDance** [sasi2006166/Fallback-Server#42]
FallBack Server doesn't direct players to the hub after their server goes down.
Velocity 3.3.0-SNAPSHOT

```
[02:16:44 INFO]: [server connection] LucyMew19 -> survival has disconnected
[02:16:44 ERROR]: Couldn't pass KickedFromServerEvent to fallbackservervelocity 3.2.0-Beta2
java.lang.NullPointerException: Cannot invoke "com.velocitypowered.api.proxy.server.RegisteredServer.getServerInfo()" because "server" is null
        at me.candiesjar.fallbackserver.listeners.FallbackListener.lambda$onPlayerKick$0(FallbackListener.java:79) ~[?:?]
        at java.base/java.util.ArrayList.removeIf(ArrayList.java:1672) ~[?:?]
        at java.base/java.util.ArrayList.removeIf(ArrayList.java:1660) ~[?:?]
        at me.candiesjar.fallbackserver.listeners.FallbackListener.onPlayerKick(FallbackListener.java:79) ~[?:?]
        at me.candiesjar.fallbackserver.listeners.Lmbda$47.execute(Unknown Source) ~[?:?]
        at com.velocitypowered.proxy.event.UntargetedEventHandler$VoidHandler.lambda$buildHandler$0(UntargetedEventHandler.java:56) ~[velocity.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
        at com.velocitypowered.proxy.event.VelocityEventManager.fire(VelocityEventManager.java:598) ~[velocity.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
        at com.velocitypowered.proxy.event.VelocityEventManager.lambda$fire$5(VelocityEventManager.java:479) ~[velocity.jar:3.3.0-SNAPSHOT (git-5154f029-b404)]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
        at java.base/java.lang.Thread.run(Thread.java:840) [?:?]
```
[config.yml.txt](https://github.com/user-attachments/files/16791209/config.yml.txt)

**Comment by BakiDance** [comment]
Forgot to add: The plugin works as expected after the proxy restarts (players are redirected as they should be). After a few hours, the plugin breaks again, though.
